### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by vahidAK** [UCSC-nanopore-cgl/signalAlign#25]
Hi @mitenjain 

I got this error after installation when I run make test:

    from pysam import FastaFile, AlignmentFile, AlignedSegment, AlignmentHeader
    ImportError: cannot import name 'AlignmentHeader'
I would appreciate if you could help me with this matter.
Thanks,
Vahid

**Comment by mitenjain** [comment]
Hi @vahidAK 

It may be worth checking the requirements from the installation: https://github.com/UCSC-nanopore-cgl/signalAlign#requirements

Could you also check if your make and pip install were successful (in that order)? And what OS are you running on?

Also tagging @adbailey4 if he has further suggestions.

Best regards,
Miten, Andrew

**Comment by vahidAK** [comment]
Thanks, @mitenjain 
I am working on a shared server and I do not have sudo access. The system guys installed the dependencies and I made a python3.5 virtual environment by conda. I also installed pysam by conda

**Comment by vahidAK** [comment]
BTW, I tried to extract fastq from guppy fast5 files but I faced this error:
Fastq not found in: /projects/vakbari_prj/scratch/GSC_prometion_guppybasecalled/B77078/workspace/PAD92039_147a95e3ada75e662f57d6620b05918197bdede7_0.fast5

**Comment by mitenjain** [comment]
Thank you @vahidAK 

The reads are fed directly from the fastq file that is written out by guppy. The read to signal mapping is done via indexing (right now this requires single fast5 files). 

We are working on a major overhaul of signalAlign installation to binarize many things. This will likely take around 4-6 weeks but should make the code substantially easier to use and customize. 

Thank you for being patient.
