### ISSUE TITLE
Make test error

### ISSUE THREAD

**Issue by dsperley** [UCSC-nanopore-cgl/signalAlign#28]
Hi, 
I'm trying to install signalAlign and keep getting some errors during make test.

test_pUC_r9_reads_5mer (__main__.SignalAlignAlignmentTest) ... Traceback (most recent call last):
  File "/lower_bay/home/danielle.perley/installations/signalAlign/bin/runSignalAlign", line 12, in <module>
    from signalalign.filter_reads import filter_reads, filter_reads_to_string_wrapper
ImportError: No module named signalalign.filter_reads
FAIL

======================================================================
FAIL: test_Ecoli1D_reads_5mer (__main__.SignalAlignAlignmentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".//src/signalalign/tests/test_runSignalAlign.py", line 180, in test_Ecoli1D_reads_5mer
    extra_args="-T=../models/testModelR9p4_5mer_acegt_template.model ")
  File ".//src/signalalign/tests/test_runSignalAlign.py", line 97, in check_alignments
    self.assertTrue(result == 0, "Error running signalAlign. Command was {}".format(alignment_command))
AssertionError: False is not true : Error running signalAlign. Command was /lower_bay/home/danielle.perley/installations/signalAlign/bin/runSignalAlign run2 -d=/lower_bay/home/danielle.perley/installations/signalAlign/tests/minion_test_reads/1D/ --bwa_reference=/lower_bay/home/danielle.perley/installations/signalAlign/tests/test_sequences/E.coli_K12.fasta -smt=threeState -o=./signalAlign_unittest/ -T=../models/testModelR9p4_5mer_acegt_template.model

**Comment by wgosal** [comment]
I got the same error (i.e. ImportError: No module named signalalign.filter_reads) - using MacOS High Sierra.

I changed the top line in runSignalAlign from 

#!/usr/bin/env python
to
#!/usr/bin/env python3

This now runs without this error and goes further into the process. However the "make test" still fails a lot latter on. Using gcc-9, python 3.6 & python 2.7 also.
