### ISSUE TITLE
docker running error

### ISSUE THREAD

**Issue by liuyangzzu** [UCSC-nanopore-cgl/signalAlign#34]
Dear author, I am very interested in your program. But when I try to run your example using Docker image, it always failed. Would you please help me to figure out the problems? Or anyone can run through the example? Thank you!

Below is my command line:
```
git clone https://github.com/UCSC-nanopore-cgl/signalAlign.git
cd signalAlign/

singularity exec docker://ucscbailey/signalalign:v1.0.0  runSignalAlign.py run --config tests/runSignalAlign-config.json
```

Error message is as follows:
```
Traceback (most recent call last):
  File "/opt/venv/bin/runSignalAlign.py", line 323, in <module>
    main()
  File "/opt/venv/bin/runSignalAlign.py", line 157, in main
    samples = [SignalAlignSample(working_folder=temp_folder, **s) for s in sa_args]
  File "/opt/venv/bin/runSignalAlign.py", line 157, in <listcomp>
    samples = [SignalAlignSample(working_folder=temp_folder, **s) for s in sa_args]
TypeError: __init__() got an unexpected keyword argument 'degenerate'
```

Not sure if there is anyone take in charge of this repository. Thank you!

**Comment by adbailey4** [comment]
I removed the degenerate keyword argument from the config file and updated the documentation to make the test run for the docker image. Closing once tests pass for pull request
